export {default as Contact} from './Contact/Contact'
export {default as Footer} from './Footer/Footer'
export {default as Landing} from './Landing/Landing'
export {default as Navbar} from './Navbar/Navbar'
export {default as Team} from './Team/Team'